- name: "Instalando servidor DHCP..."
  apt:
    name: isc-dhcp-server

- name: "Modificando /etc/default/isc-dhcp-server"
  ansible.builtin.template:
    src: etc/default/isc-dhcp-server
    dest: /etc/default/isc-dhcp-server
    owner: root
    group: root
    mode: '0644'
  notify:
    - reiniciar_dhcp

- name: "Modificando /etc/dhcp/dhcpd.conf"
  ansible.builtin.template:
    src: etc/dhcp/dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - reiniciar_dhcp
 